### ISSUE TITLE
安卓手机安装不了

### ISSUE THREAD

**Issue by LHC12580** [ranlychan/PieExpressTracking#2]

**Comment by ranlychan** [comment]
PieExpressTracking目前只有支持WearOS智能手表的安装包

**Comment by LHC12580** [comment]
好的，收到，能做一个查快递的APP吗？
因为现在的查快递，都需要手机号码验证码，或者下载快递app才能查快递？非常不方便！



---原始邮件---
发件人: "Canyi ***@***.***&gt;
发送时间: 2024年1月22日(周一) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ranlychan/PieExpressTracking] 安卓手机安装不了 (Issue #2)




 
PieExpressTracking目前只有支持WearOS智能手表的安装包
